name: Compose test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  grading:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Runs docker compose
        uses: ACR-Wonderland/docker-compose-action-test@v1 

      - name: Debug Workspace Structure
        run: |
          echo "Current working directory $(pwd)"
          echo "GITHUB_WORKSPACE = ${{ github.workspace }}"
          echo "Contents of GITHUB_WORKSPACE:"
          ls -la ${{ github.workspace }}
          echo "Contents of current directory:"
          ls -la
